name: shelf_injection_router
version: 0.1.1
description: Shelf middleware that provides routing with route params, handler injection and params validation.
homepage: https://github.com/octobyte/shelf_injection_router
author: Thomas Profelt <tom@octobyte.at>

dependencies:
  shelf: ">=0.5.0+1 <0.6.0"
  shelf_exception_response: ">=0.1.0 <0.2.0"
  http_server: ">=0.9.2 <0.10.0"

dev_dependencies:
  unittest: any
  mock: any

environment:
  sdk: ">=1.3.0"